#!/bin/bash
# chkconfig: 2345 98 02
#
# description: SimpleLogs Script
# processname: simplelogs
#
### BEGIN INIT INFO
# Provides:          simplelogs
# Required-Start:    
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description: SimpleLogs init script
# Description: SimpleLogs application init script
### END INIT INFO

ENV=production
NAME=simplelogs
PM2=/usr/lib/node_modules/pm2/bin/pm2
NODE=/usr/bin/nodejs
USER=root
APPLICATION_PATH=/var/www/start.js

export HOME="/home/vagrant"

super() {
    sudo -u $USER $*
}

start() {
    echo "Starting $NAME"
    super NODE_ENV=$ENV $NODE $PM2 start $APPLICATION_PATH --name $NAME
}
 
stop() {
    super $NODE $PM2 dump
    super $NODE $PM2 delete all
    super $NODE $PM2 kill
}
 
restart() {
    echo "Restarting $NAME"
    stop
    start
}
 
reload() {
    echo "Reloading $NAME"
    super $NODE $PM2 reload all
}
 
status() {
    echo "Status for $NAME:"
    $NODE $PM2 list
    RETVAL=$?
}
 
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    reload)
        reload
        ;;
    *)
        echo "Usage: {start|stop|status|restart|reload}"
        exit 1
        ;;
esac
exit $RETVAL